services:
  server:
    build:
      context: .
    image: event-scheduler
    env_file:
      - .env
    ports:
      - "8001:8000"

  cli:
    image: event-scheduler
    env_file:
      - .env
    command: ["python", "-m", "scheduler_app.cli"]
    volumes:
      - db-data:/app/data
    profiles:
      - cli

volumes:
  db-data:
